## <center> Assignment 3  </center>

## <center> SVM and Pipelines  </center>

In [1]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import RobustScaler
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
import numpy as np

# loading and spliting the data 
#Task 1
wines = load_wine()
#Task 2
X_train, X_test, y_train, y_test = train_test_split(wines.data, wines.target, random_state=1410)

In [2]:
#Task 3
svm = SVC()
cross_val_score(svm,X_train,y_train)

array([0.66666667, 0.74074074, 0.74074074, 0.69230769, 0.65384615])

In [3]:
#Task 4
svm.fit(X_train,y_train)
accuracy = svm.score(X_test, y_test)
print("The accuracy of SVM with default values of parameter is:",accuracy)
test_error_rate = 1 - accuracy
print("The test error rate of SVM is",test_error_rate)

The accuracy of SVM with default values of parameter is: 0.7333333333333333
The test error rate of SVM is 0.2666666666666667


    On comparing the cross validation score and the test error rate of SVM obtained in task 3 and task 4, we can say that it is similar for the 2nd and 3rd array value of cross validation score but the accuracy is higher than that of other scores obtained.

In [4]:
#Task 5
pipe1 = make_pipeline(MinMaxScaler(), SVC())
pipe1.fit(X_train, y_train)

Pipeline(steps=[('minmaxscaler', MinMaxScaler()), ('svc', SVC())])

In [5]:
pipe2 = make_pipeline(Normalizer(), SVC())
pipe2.fit(X_train, y_train)

Pipeline(steps=[('normalizer', Normalizer()), ('svc', SVC())])

In [6]:
pipe3 = make_pipeline(StandardScaler(), SVC())
pipe3.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])

In [7]:
pipe4 = make_pipeline(RobustScaler(), SVC())
pipe4.fit(X_train, y_train)

Pipeline(steps=[('robustscaler', RobustScaler()), ('svc', SVC())])

In [8]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid1 = GridSearchCV(pipe1, param_grid=param_grid, cv=5)
grid1.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid1.best_score_)
print("Test set score:", grid1.score(X_test, y_test))
print("Best parameters:", grid1.best_params_)

Best cross-validation accuracy: 0.9925925925925926
Test set score: 0.9333333333333333
Best parameters: {'svc__C': 0.1, 'svc__gamma': 1}


In [9]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid2 = GridSearchCV(pipe2, param_grid=param_grid, cv=5)
grid2.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid2.best_score_)
print("Test set score:", grid2.score(X_test, y_test))
print("Best parameters:", grid2.best_params_)

Best cross-validation accuracy: 0.9242165242165242
Test set score: 0.8888888888888888
Best parameters: {'svc__C': 100, 'svc__gamma': 100}


In [10]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid3 = GridSearchCV(pipe3, param_grid=param_grid, cv=5)
grid3.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid3.best_score_)
print("Test set score:", grid3.score(X_test, y_test))
print("Best parameters:", grid3.best_params_)

Best cross-validation accuracy: 0.9851851851851852
Test set score: 0.9777777777777777
Best parameters: {'svc__C': 1, 'svc__gamma': 0.1}


In [11]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid4 = GridSearchCV(pipe4, param_grid=param_grid, cv=5)
grid4.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid4.best_score_)
print("Test set score:", grid4.score(X_test, y_test))
print("Best parameters:", grid4.best_params_)

Best cross-validation accuracy: 0.9925925925925926
Test set score: 0.9555555555555556
Best parameters: {'svc__C': 1, 'svc__gamma': 0.1}


    Based on the test score, I have selected the grid 3(StandardScalar) to predict the test labels and to calculate accuracy of the model. 

In [12]:
#Task 6
yhat = grid3.predict(X_test)

In [13]:
my_accuracy = accuracy_score(y_test, yhat, normalize=False) / float(y_test.size)
my_accuracy

0.9777777777777777

<center> Task 8 </center>

In [14]:
mlp = MLPClassifier(solver='lbfgs', activation='tanh', random_state=1410,
hidden_layer_sizes=[10]).fit(X_train,y_train)

In [15]:
cross_val_score(mlp,X_train,y_train)

array([0.37037037, 0.37037037, 0.37037037, 0.38461538, 0.38461538])

In [16]:
mlp.fit(X_train,y_train)
accuracy = mlp.score(X_test, y_test)
print("The accuracy of MLP is:",accuracy)
test_error_rate = 1 - accuracy
print("The test error rate of MLP is",test_error_rate)

The accuracy of MLP is: 0.4666666666666667
The test error rate of MLP is 0.5333333333333333


    On comparing the cross validation score and accuracy of MLP, it is observed that the acuuracy of MLP is higher when compared to the cross validation scores obtained. 

In [17]:
pipe = Pipeline(steps=[('mlpc', mlp)])

In [18]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('mlpc',
                 MLPClassifier(activation='tanh', hidden_layer_sizes=[10],
                               random_state=1410, solver='lbfgs'))])

In [19]:
yhat = pipe.predict(X_test)
my_accuracy = accuracy_score(y_test, yhat, normalize=False) / float(y_test.size)
my_accuracy

0.4666666666666667

<center>All the Steps with USPS dataset</center> 

In [20]:
#Task 1
usps_data = np.genfromtxt("zip.train")
usps_label = np.genfromtxt("zip.test")
usps = np.concatenate((usps_data,usps_label),axis=0)

In [21]:
#Task2
X_train, X_test, y_train, y_test = train_test_split(usps[:,1:], usps[:,0], random_state=1410)

In [22]:
#Task 3
svm = SVC()
cross_val_score(svm,X_train,y_train)

array([0.97491039, 0.96702509, 0.97419355, 0.97058824, 0.96700143])

In [23]:
#Task 4
svm.fit(X_train,y_train)
accuracy = svm.score(X_test, y_test)
print("The accuracy of SVM with default values of parameter is:",accuracy)
test_error_rate = 1 - accuracy
print("The test error rate of SVM is",test_error_rate)

The accuracy of SVM with default values of parameter is: 0.9729032258064516
The test error rate of SVM is 0.02709677419354839


In [24]:
#Task 5
pipe1 = make_pipeline(MinMaxScaler(), SVC())
pipe1.fit(X_train, y_train)

Pipeline(steps=[('minmaxscaler', MinMaxScaler()), ('svc', SVC())])

In [25]:
pipe3 = make_pipeline(StandardScaler(), SVC())
pipe3.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])

In [ ]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid1 = GridSearchCV(pipe1, param_grid=param_grid, cv=5)
grid1.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid1.best_score_)
print("Test set score:", grid1.score(X_test, y_test))
print("Best parameters:", grid1.best_params_)

In [ ]:
param_grid = {'svc__C': [0.01, 0.1, 1, 10, 100], 'svc__gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
grid3 = GridSearchCV(pipe3, param_grid=param_grid, cv=5)
grid3.fit(X_train, y_train)
print("Best cross-validation accuracy:", grid3.best_score_)
print("Test set score:", grid3.score(X_test, y_test))
print("Best parameters:", grid3.best_params_)

In [ ]:
#Task 6
yhat = grid1.predict(X_test)

In [ ]:
my_accuracy = accuracy_score(y_test, yhat, normalize=False) / float(y_test.size)
my_accuracy

In [ ]:
mlp = MLPClassifier(solver='lbfgs', activation='tanh', random_state=1410,
hidden_layer_sizes=[10]).fit(X_train,y_train)

In [ ]:
cross_val_score(mlp,X_train,y_train)

In [ ]:
mlp.fit(X_train,y_train)
accuracy = mlp.score(X_test, y_test)
print("The accuracy of MLP is:",accuracy)
test_error_rate = 1 - accuracy
print("The test error rate of MLP is",test_error_rate)

In [ ]:
pipe = Pipeline(steps=[('mlpc', mlp)])
pipe.fit(X_train,y_train)
yhat = pipe.predict(X_test)
my_accuracy = accuracy_score(y_test, yhat, normalize=False) / float(y_test.size)
my_accuracy